// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockChart.Model;
#nullable disable
namespace StockChart.Migrations.ApplicationDbContext2Migrations
{
    [DbContext(typeof(ApplicationDbContext2))]
    [Migration("20230302040700_UserThings9")]
    partial class UserThings9
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);
            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");
                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");
                    b.HasKey("Id");
                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");
                    b.ToTable("AspNetRoles", (string)null);
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("RoleId");
                    b.ToTable("AspNetRoleClaims", (string)null);
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("AspNetUserClaims", (string)null);
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");
                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");
                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");
                    b.HasKey("LoginProvider", "ProviderKey");
                    b.HasIndex("UserId");
                    b.ToTable("AspNetUserLogins", (string)null);
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");
                    b.HasKey("UserId", "RoleId");
                    b.HasIndex("RoleId");
                    b.ToTable("AspNetUserRoles", (string)null);
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");
                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");
                    b.HasKey("UserId", "LoginProvider", "Name");
                    b.ToTable("AspNetUserTokens", (string)null);
                });
            modelBuilder.Entity("StockChart.Model.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");
                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");
                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");
                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");
                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");
                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");
                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");
                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");
                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");
                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");
                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");
                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");
                    b.HasKey("Id");
                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");
                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");
                    b.ToTable("AspNetUsers", (string)null);
                });
            modelBuilder.Entity("StockChart.Model.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");
                    b.Property<int>("Count")
                        .HasColumnType("int");
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");
                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");
                    b.Property<Guid?>("ReferalId")
                        .HasColumnType("uniqueidentifier");
                    b.Property<int>("Services")
                        .HasColumnType("int");
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("Bill");
                });
            modelBuilder.Entity("StockChart.Model.CategoryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<byte?>("Market")
                        .HasColumnType("tinyint");
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("CategoryType");
                });
            modelBuilder.Entity("StockChart.Model.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<byte>("MarketId")
                        .HasColumnType("tinyint");
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("Class");
                });
            modelBuilder.Entity("StockChart.Model.Dictionary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int?>("CategoryTypeId")
                        .HasColumnType("int");
                    b.Property<int?>("ClassId")
                        .HasColumnType("int");
                    b.Property<string>("ClassName")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");
                    b.Property<DateTime?>("FromDate")
                        .HasColumnType("datetime2");
                    b.Property<string>("Isin")
                        .HasColumnType("nvarchar(max)");
                    b.Property<int?>("Lotsize")
                        .HasColumnType("int");
                    b.Property<byte?>("Market")
                        .HasColumnType("tinyint");
                    b.Property<byte?>("MarketNavigationId")
                        .HasColumnType("tinyint");
                    b.Property<decimal>("Minstep")
                        .HasColumnType("decimal(18,2)");
                    b.Property<short?>("Oldid")
                        .HasColumnType("smallint");
                    b.Property<int?>("Scale")
                        .HasColumnType("int");
                    b.Property<string>("Securityid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("Shortname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime2");
                    b.Property<decimal>("Volperqnt")
                        .HasColumnType("decimal(18,2)");
                    b.HasKey("Id");
                    b.HasIndex("CategoryTypeId");
                    b.HasIndex("ClassId");
                    b.HasIndex("MarketNavigationId");
                    b.ToTable("Dictionary");
                });
            modelBuilder.Entity("StockChart.Model.Market", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<bool>("Structed")
                        .HasColumnType("bit");
                    b.Property<bool>("Visible")
                        .HasColumnType("bit");
                    b.HasKey("Id");
                    b.ToTable("Market");
                });
            modelBuilder.Entity("StockChart.Model.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");
                    b.Property<decimal>("PayAmount")
                        .HasColumnType("decimal(18,2)");
                    b.Property<DateTime>("PayDate")
                        .HasColumnType("datetime2");
                    b.Property<int>("Service")
                        .HasColumnType("int");
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("Payment");
                });
            modelBuilder.Entity("StockChart.Model.PushDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("PushDevice");
                });
            modelBuilder.Entity("StockChart.Model.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");
                    b.Property<string>("Header")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");
                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("Topic");
                });
            modelBuilder.Entity("StockChart.Model.TopicComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");
                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<int>("TopicId")
                        .HasColumnType("int");
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("TopicId");
                    b.HasIndex("UserId");
                    b.ToTable("UserComment");
                });
            modelBuilder.Entity("StockChart.Model.UserGameBallance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<decimal>("Ballance")
                        .HasColumnType("decimal(18,2)");
                    b.Property<byte>("PortfolioNumber")
                        .HasColumnType("tinyint");
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("UserGameBallance");
                });
            modelBuilder.Entity("StockChart.Model.UserGameOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("datetime2");
                    b.Property<byte>("PortfolioNumber")
                        .HasColumnType("tinyint");
                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");
                    b.Property<int>("Quantity")
                        .HasColumnType("int");
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("UserGameOrder");
                });
            modelBuilder.Entity("StockChart.Model.UserGameShare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("DictionaryId")
                        .HasColumnType("int");
                    b.Property<byte>("PortfolioNumber")
                        .HasColumnType("tinyint");
                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");
                    b.Property<int>("Quantity")
                        .HasColumnType("int");
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("DictionaryId");
                    b.HasIndex("UserId");
                    b.ToTable("UserGameShare");
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("StockChart.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("StockChart.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("StockChart.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("StockChart.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
            modelBuilder.Entity("StockChart.Model.Bill", b =>
                {
                    b.HasOne("StockChart.Model.ApplicationUser", "User")
                        .WithMany("Bills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("User");
                });
            modelBuilder.Entity("StockChart.Model.Dictionary", b =>
                {
                    b.HasOne("StockChart.Model.CategoryType", "CategoryType")
                        .WithMany("Dictionaries")
                        .HasForeignKey("CategoryTypeId");
                    b.HasOne("StockChart.Model.Class", "Class")
                        .WithMany("Dictionaries")
                        .HasForeignKey("ClassId");
                    b.HasOne("StockChart.Model.Market", "MarketNavigation")
                        .WithMany("Dictionaries")
                        .HasForeignKey("MarketNavigationId");
                    b.Navigation("CategoryType");
                    b.Navigation("Class");
                    b.Navigation("MarketNavigation");
                });
            modelBuilder.Entity("StockChart.Model.Payment", b =>
                {
                    b.HasOne("StockChart.Model.ApplicationUser", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("User");
                });
            modelBuilder.Entity("StockChart.Model.PushDevice", b =>
                {
                    b.HasOne("StockChart.Model.ApplicationUser", "User")
                        .WithMany("PushDevices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("User");
                });
            modelBuilder.Entity("StockChart.Model.Topic", b =>
                {
                    b.HasOne("StockChart.Model.ApplicationUser", "User")
                        .WithMany("Topics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("User");
                });
            modelBuilder.Entity("StockChart.Model.TopicComment", b =>
                {
                    b.HasOne("StockChart.Model.Topic", "Topic")
                        .WithMany("UserComments")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("StockChart.Model.ApplicationUser", "User")
                        .WithMany("TopicComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Topic");
                    b.Navigation("User");
                });
            modelBuilder.Entity("StockChart.Model.UserGameBallance", b =>
                {
                    b.HasOne("StockChart.Model.ApplicationUser", "User")
                        .WithMany("UserGameBallances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("User");
                });
            modelBuilder.Entity("StockChart.Model.UserGameOrder", b =>
                {
                    b.HasOne("StockChart.Model.ApplicationUser", "User")
                        .WithMany("UserGameOrders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("User");
                });
            modelBuilder.Entity("StockChart.Model.UserGameShare", b =>
                {
                    b.HasOne("StockChart.Model.Dictionary", "Dictionary")
                        .WithMany()
                        .HasForeignKey("DictionaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("StockChart.Model.ApplicationUser", "User")
                        .WithMany("UserGameShares")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Dictionary");
                    b.Navigation("User");
                });
            modelBuilder.Entity("StockChart.Model.ApplicationUser", b =>
                {
                    b.Navigation("Bills");
                    b.Navigation("Payments");
                    b.Navigation("PushDevices");
                    b.Navigation("TopicComments");
                    b.Navigation("Topics");
                    b.Navigation("UserGameBallances");
                    b.Navigation("UserGameOrders");
                    b.Navigation("UserGameShares");
                });
            modelBuilder.Entity("StockChart.Model.CategoryType", b =>
                {
                    b.Navigation("Dictionaries");
                });
            modelBuilder.Entity("StockChart.Model.Class", b =>
                {
                    b.Navigation("Dictionaries");
                });
            modelBuilder.Entity("StockChart.Model.Market", b =>
                {
                    b.Navigation("Dictionaries");
                });
            modelBuilder.Entity("StockChart.Model.Topic", b =>
                {
                    b.Navigation("UserComments");
                });
#pragma warning restore 612, 618
        }
    }
}
