<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup Label="Configuration" Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TypeScriptTarget>ES2021</TypeScriptTarget>
    <TypeScriptSourceMap>False</TypeScriptSourceMap>
    <TypeScriptCompileOnSaveEnabled>False</TypeScriptCompileOnSaveEnabled>
    <TypeScriptNoEmitOnError>False</TypeScriptNoEmitOnError>
  </PropertyGroup>
  <PropertyGroup Label="Configuration" Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TypeScriptTarget>ES2021</TypeScriptTarget>
    <TypeScriptSourceMap>False</TypeScriptSourceMap>
    <TypeScriptCompileOnSaveEnabled>False</TypeScriptCompileOnSaveEnabled>
    <TypeScriptNoEmitOnError>False</TypeScriptNoEmitOnError>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-StockChart-17668cf8-5b85-45f9-a2b3-df2dc7d600e5</UserSecretsId>
    <OutputType>WinExe</OutputType>
    <DefaultItemExcludes>$(DefaultItemExcludes);UpdateService\**\*;CommonApi\**\*</DefaultItemExcludes>
    <NoWarn>$(NoWarn);CS8600;CS8601;CS8602;CS8603;CS8604;CS8613;CS8625;CS8629;CS8632</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Protobuf Include="Protos\greet.proto" GrpcServices="Client" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Repository\Services\PaymentOperations.cs" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Pages\SearchTicker.cshtml.cs" />
    <Content Include="Repository\Services\PaymentOperations.cs" />
  </ItemGroup>
  <ItemGroup Condition="Exists('wwwroot\bower_components')">
    <Content Include="wwwroot\bower_components\**\*" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Accord.Math" Version="3.8.0" />
    <PackageReference Include="ConcurrentHashSet" Version="1.3.0" />    
    <PackageReference Include="Keras.NET" Version="3.8.5" />    
    <PackageReference Include="Markdig" Version="0.45.0" />
    <PackageReference Include="Microsoft.AspNetCore.SpaServices" Version="3.1.32" />
    <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="10.0.2" />
    <PackageReference Include="Microsoft.CodeAnalysis" Version="5.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Features" Version="5.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.0.0" />
    <PackageReference Include="Microsoft.ML" Version="5.0.0" />
    <PackageReference Include="Microsoft.ML.FastTree" Version="5.0.0" />
    <PackageReference Include="NLog" Version="6.1.0" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="6.1.1" />
    <PackageReference Include="NumSharp" Version="0.30.0" />
    <PackageReference Include="SciSharp.TensorFlow.Redist" Version="2.16.0" />
    <PackageReference Include="SendGrid" Version="9.29.3" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.1" />    
    <PackageReference Include="TensorFlow.NET" Version="0.150.0" />
  
    <PackageReference Include="Wangkanai.Detection" Version="8.20.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="CommonApi\CommonApi.csproj" />
    <ProjectReference Include="..\StockChart.EventBus.RabbitMQ.DependencyInjection\StockChart.EventBus.RabbitMQ.DependencyInjection.csproj" />
    <ProjectReference Include="..\StockChart.EventBus.RabbitMQ\StockChart.EventBus.RabbitMQ.csproj" />
    <ProjectReference Include="..\StockChart.EventBus\StockChart.EventBus.csproj" />
    <ProjectReference Include="..\StockChart.Data\StockChart.Data.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="CommonApi\**\*.cs" />
    <Compile Remove="UpdateService\**\*.cs" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Model\DividendsDtos.cs" />
    <Compile Remove="Model\FinancialStatementsDtos.cs" />
    <Compile Remove="Model\MoexApiDtos.cs" />
    <Compile Remove="Model\MoexSyncDtos.cs" />
    <Compile Remove="Model\RecommendationDtos.cs" />
    <Compile Remove="Model\ShareholdersDtos.cs" />
    <Compile Remove="Repository\Interfaces\IBillingRepository.cs" />
    <Compile Remove="Repository\Interfaces\IDividendsMoexService.cs" />
    <Compile Remove="Repository\Interfaces\IFinancialStatementsService.cs" />
    <Compile Remove="Repository\Interfaces\IMoexApiService.cs" />
    <Compile Remove="Repository\Interfaces\IMoexSyncService.cs" />
    <Compile Remove="Repository\Interfaces\IShareholdersRecommendationsService.cs" />
    <Compile Remove="Repository\Interfaces\IYooMoneyRepository.cs" />
    <Compile Remove="Repository\Moex\MoexOpenPositionsDeserializer.cs" />
    <Compile Remove="Repository\Services\BatchImportOpenPositionsServiceNew.cs" />
    <Compile Remove="Repository\Services\BillingRepository.cs" />
    <Compile Remove="Repository\Services\DividendsMoexService.cs" />
    <Compile Remove="Repository\Services\FinancialStatementsService.cs" />
    <Compile Remove="Repository\Services\MoexApiService.cs" />
    <Compile Remove="Repository\Services\MoexSyncService.cs" />
    <Compile Remove="Repository\Services\ShareholdersRecommendationsService.cs" />
    <Compile Remove="Repository\Services\YooMoneyOptions.cs" />
    <Compile Remove="Repository\Services\YooMoneyRepository.cs" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Messages\" />
  </ItemGroup>
</Project>
