<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.11.64" />
    <PackageReference Include="newtonsoft.json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Class1.cs" />
    <Compile Remove="Class2.cs" />
    <Compile Remove="Class3.cs" />
    <Compile Remove="finam_parsing.cs" />
    <Compile Remove="models\\models.cs" />
  </ItemGroup>

</Project>
